name: build
'on': [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
            c_compiler: gcc
          - os: ubuntu-latest
            cpp_compiler: clang++
            c_compiler: clang
          - os: macos-latest
            cpp_compiler: clang++
            c_compiler: clang
          - os: windows-latest
            cpp_compiler: cl
            c_compiler: cl
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      id: setup
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Configure
      run: >
        cmake
        -S ${{ github.workspace }}
        -B ${{ steps.setup.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBT_BUILD_TESTS=1
    - name: Build
      run: cmake --build ${{ steps.setup.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{ steps.setup.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
